- name: "generate id_rsa key"
  user:
    name: "{{ username }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
  tags: user

- name: "set as default shell"
  user:
    name: "{{ username }}"
    shell: /usr/local/bin/zsh
  become: yes
  tags: user