- name: "make sure the python 2.7 folder exists (needed for passlib)."
  file:
    path: /Users/{{ username }}/Library/Python/2.7/lib/python/site-packages
    state: directory
  become: yes
  tags: user

- name: "add the pyhton homebrew setup file (needed for passlib)."
  copy:
    src: "{{ role_path }}/files/homebrew.pth"
    dest: "/Users/{{ username }}/Library/Python/2.7/lib/python/site-packages/homebrew.pth"
  become: yes
  tags: user

- name: "generate id_rsa key"
  user:
    name: "{{ username }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
  tags: user

- name: "set as default shell"
  user:
    name: "{{ username }}"
    shell: /usr/local/bin/zsh
  become: yes
  tags: user