- name: check stat of default vscode configuration folder
  stat:
    path: "/Users/{{ username }}/Library/Application Support/Code/User"
  register: vscode_config
  tags: vscode

- name: remove the default vscode configuration folder
  file:
    path: "/Users/{{ username }}/Library/Application Support/Code/User"
    state: absent
  when: vscode_config.stat.isdir is defined and vscode_config.stat.isdir
  tags: vscode

- name: copy our custom vscode configuration
  file:
    src: "{{ role_path }}/files/User"
    dest: "/Users/{{ username }}/Library/Application Support/Code/User"
    state: link
    force: yes
  tags: vscode

- name: check stat of default vscode extension folder
  stat:
    path: "/Users/{{ username }}/.vscode/extensions"
  register: vscode_extensions
  tags: vscode

- name: remove the default vscode extension folder
  file:
    path: "/Users/{{ username }}/.vscode/extensions"
    state: absent
  when: vscode_extensions.stat.isdir is defined and vscode_extensions.stat.isdir
  tags: vscode

- name: copy our custom vscode extension
  file:
    src: "{{ role_path }}/files/extensions"
    dest: "/Users/{{ username }}/.vscode/extensions"
    state: link
    force: yes
  tags: vscode