<?php
return PhpCsFixer\Config::create()
	->setRiskyAllowed(true)
    ->setRules(array(
		'psr0' => false,
		'@PSR2' => true,
		'binary_operator_spaces' => true,
		'blank_line_before_return' => true,
		'cast_spaces' => true,
		'hash_to_slash_comment' => true,
		'method_separation' => true,
		'new_with_braces' => true,
		'no_blank_lines_after_class_opening' => true,
		'no_blank_lines_after_phpdoc' => true,
		'no_blank_lines_before_namespace' => true,
		'no_extra_consecutive_blank_lines' => true,
		'no_singleline_whitespace_before_semicolons' => true,
		'no_unused_imports' => true,
		'ordered_imports' => true,
		'phpdoc_align' => true,
		'phpdoc_no_empty_return' => true,
		'phpdoc_order' => true,
		'phpdoc_scalar' => true,
		'phpdoc_separation' => true,
		'phpdoc_trim' => true,
		'short_scalar_cast' => true,
		'simplified_null_return' => false,
		'single_quote' => true,
		'ternary_operator_spaces' => true,
		'trim_array_spaces' => true,
		'whitespace_after_comma_in_array' => true,
		'function_typehint_space' => true,
		'lowercase_cast' => true,
		'native_function_casing' => true,
		'no_empty_comment' => true,
		'no_empty_phpdoc' => true,
		'no_multiline_whitespace_before_semicolons' => true,
		'no_useless_else' => true,
		'no_useless_return' => true,
		'ordered_class_elements' => true,
		'phpdoc_add_missing_param_annotation' => ['only_untyped' => false],
		'array_syntax' => array('syntax' => 'short'),
		'concat_space' => ['spacing' => 'one']
    ));

