---
- name: "check if oh-my-zsh is installed"
  stat: path=/Users/{{ username }}/.oh-my-zsh
  register: oh_my_zsh_installed
  tags: zsh

- name: "install oh-my-zsh"
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  when: oh_my_zsh_installed.stat.exists == false
  tags: zsh

- name: "set zhs avit theme"
  lineinfile:
    path: /Users/{{ username }}/.zshrc
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="avit"'
  tags: zsh

- name: "set zhs plugins"
  lineinfile:
    path: /Users/{{ username }}/.zshrc
    regexp: '^plugins='
    line: 'plugins=(docker docker-compose git)'
  tags: zsh

- name: "set zhs sintax highlighting"
  lineinfile:
    path: /Users/{{ username }}/.zshrc
    regexp: '^source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh'
    line: 'source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh'
  tags: zsh

- name: 'set backward-word key bind'
  lineinfile:
    path: /Users/{{ username }}/.zshrc
    regexp: '^bindkey "\[D"'
    line: 'bindkey "[D" backward-word'
  tags: zsh

- name: 'set forward-word key bind'
  lineinfile:
    path: /Users/{{ username }}/.zshrc
    regexp: '^bindkey "\[C"'
    line: 'bindkey "[C" forward-word'
  tags: zsh
