---
- name: "check if oh-my-zsh is installed"
  stat: path=/Users/{{ username }}/.oh-my-zsh
  register: oh_my_zsh_installed
  tags: zsh

- name: "install oh-my-zsh"
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  when: oh_my_zsh_installed.stat.exists == false
  tags: zsh

- name: "set zhs avit theme"
  lineinfile:
    path: /Users/{{ username }}/.zshrc
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="avit"'
  tags: zsh

- name: "set zhs plugins"
  lineinfile:
    path: /Users/{{ username }}/.zshrc
    regexp: '^plugins='
    line: 'plugins=(docker docker-compose git)'
  tags: zsh

- name: "set zhs sintax highlighting"
  lineinfile:
    path: /Users/{{ username }}/.zshrc
    regexp: '^source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh'
    line: 'source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh'
  tags: zsh

- name: "set the iterm profile"
  copy:
    src: roles/zsh/files/com.googlecode.iterm2.plist
    dest: /Users/{{ username }}/Library/Preferences/com.googlecode.iterm2.plist
  register: iterm_profile
  tags: zsh

- name: "reload iterm profile"
  shell: defaults read com.googlecode.iterm2
  when: iterm_profile.changed
  tags: zsh
