dock_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences
  - Calendar
  - Terminal

dock_to_add:
  - name: iTerm
    path: /Applications/iTerm.app
    pos: 1
  - name: Visual Studio Code
    path: /Applications/Visual Studio Code.app
    pos: 2
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 3
  - name: Slack
    path: /Applications/Slack.app
    pos: 4
  - name: Sequel Pro
    path: /Applications/Sequel Pro.app
    pos: 5
  - name: KeePassX
    path: /Applications/KeePassX.app
    pos: 6
  - name: Spotify
    path: /Applications/Spotify.app
    pos: 7