dock_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences
  - Calendar
 
dock_to_add:
  - name: Terminal
    path: /Applications/Utilities/Terminal.app
    pos: 1
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 2
  - name: Slack
    path: /Applications/Slack.app
    pos: 3
  - name: Sequel Pro
    path: /Applications/Sequel Pro.app
    pos: 4
  - name: KeePassX
    path: /Applications/KeePassX.app
    pos: 5
  - name: Spotify
    path: /Applications/Spotify.app
    pos: 6